export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST';
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS';
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE';

export const PLACED_ORDER_REQUEST = 'PLACED_ORDER_REQUEST';
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDER_SUCCESS';
export const PLACED_ORDER_FAILURE = 'PLACED_ORDER_FAILURE';

export const DELIVERED_ORDER_REQUEST = 'DELIVERED_ORDER_REQUEST';
export const DELIVERED_ORDER_SUCCESS = 'DELIVERED_ORDER_SUCCESS';
export const DELIVERED_ORDER_FAILURE = 'DELIVERED_ORDER_FAILURE';

export const CANCELLED_ORDER_REQUEST = 'CANCELLED_ORDER_REQUEST';
export const CANCELLED_ORDER_SUCCESS = 'CANCELLED_ORDER_SUCCESS';
export const CANCELLED_ORDER_FAILURE = 'CANCELLED_ORDER_FAILURE';

export const SHIPPED_ORDER_REQUEST = 'SHIPPED_ORDER_REQUEST';
export const SHIPPED_ORDER_SUCCESS = 'SHIPPED_ORDER_SUCCESS';
export const SHIPPED_ORDER_FAILURE = 'SHIPPED_ORDER_FAILURE';

export const DELETED_ORDER_REQUEST = 'DELETED_ORDER_REQUEST';
export const DELETED_ORDER_SUCCESS = 'DELETED_ORDER_SUCCESS';
export const DELETED_ORDER_FAILURE = 'DELETED_ORDER_FAILURE';



